auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: info
  grpc_server_max_concurrent_streams: 1000

common:
  instance_addr: 127.0.0.1
  path_prefix: /tmp/loki
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

limits_config:
  # Experimental; keep if you want MVQs. Remove if Loki warns at startup.
  enable_multi_variant_queries: true

schema_config:
  configs:
    - from: 2025-09-16
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093
  # The blocks below are safe defaults for local filesystem rules.
  enable_api: true
  ring:
    kvstore:
      store: inmemory
  storage:
    type: local
    local:
      directory: /tmp/loki/rules
  rule_path: /tmp/loki/rules-temp

frontend:
  # Default is protobuf; keep or remove as you prefer.
  encoding: protobuf
