package com.trade.frankenstein.trader.enums;

/**
 * Context in which advice was created or executed
 */
public enum ExecutionContext {

    MANUAL("Created manually by user"),
    AUTO("Generated automatically by strategy"),
    RISK_TRIGGERED("Triggered by risk management system"),
    STRATEGY("Generated by trading strategy"),
    EMERGENCY("Emergency risk control action"),
    REBALANCE("Portfolio rebalancing action"),
    HEDGE("Risk hedging operation"),
    SCALP("High-frequency scalping"),
    SWING("Swing trading position"),
    ARBITRAGE("Arbitrage opportunity");

    private final String description;

    ExecutionContext(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public boolean isAutomated() {
        return this != MANUAL;
    }

    public boolean isRiskRelated() {
        return this == RISK_TRIGGERED || this == EMERGENCY || this == HEDGE;
    }
}
